dontnod/nimp

- nimp/command.py
Fix crash for non key-value parameters
> Handle "flags" in free_parameters

- nimp/base_commands/run.py
- nimp/base_platforms/desktop.py
- nimp/sys/platform.py
Reverts dontnod/nimp#8 because merged by mistake sorry
> Revert "Turn 'run' into a CommandGroup + add console operations"

- nimp/build.py
- nimp/environment.py
- nimp/ue4/build.py
- nimp/unreal.py
Prepare nim build for ue5 compilation
> Ue5 compat

- nimp/base_commands/build.py
- nimp/unreal_engine/build.py
- nimp/utils/git.py
You  have to pass --ubt-versioning flag, a revision through --revision <revision>
and a branch with nimp --branche <branch>.
There is a cheap check so we recognize full git commit shas from the
rest.
This is especially useful for cis build systems.
> Build: Implement ubt versioning

- nimp/base_commands/build.py
Previous behaviour for non unreal project environment would be to look
for the sln in the working dir and using the first one found.
Can now use --sln to provide the path to the file
> Add --sln arg to Build command

- nimp/base_commands/create_loadlist.py
Takes most changes from #45 and #39.
> create-loadlist: various improvements + add dry_run and slicing

- nimp/base_commands/check.py
This flags lets users search for specific processes regardless of workspace.
> Check: add --filters flag to nimp check processes

- nimp/base_commands/create_loadlist.py
checking return code is easier in scripting context than parsing json
> CreateLoadlist: morph check-empty to error-on-empty

- nimp/base_commands/run.py
- nimp/unreal.py
Nimp run commandlet and nimp run unreal_cli are now both able to support user-config files
> Run: refacto commandlet and unreal_cli so they both support user-config

- nimp/artifacts.py
- nimp/base_commands/upload_fileset.py
leftover of a test that we're not using in the end.
> upload_fileset: remove unused dir tmp code

- nimp/base_commands/package.py
Through conf files lookup or nimp project config
> Packaging: support ForSubmission flag

- nimp/base_commands/package.py
This allows to use 'binary_version' and 'content_version' in the ProjectVersion.
Only the last commit is to review here. The others are from #69
> package command --write-project-revisions allow to have a format in the version

- nimp/base_platforms/__init__.py
- nimp/base_platforms/basegdk.py
- nimp/base_platforms/wingdk.py
- nimp/base_platforms/xsx.py
Small code factoring with XSX for common code with wingdk
> Add WinGDK as a platform.

- nimp/base_commands/upload.py
- nimp/build.py
- nimp/symstore.py
Also remove the ZIP compress as it works nowhere (not even in Microsoft own tools...)
https://github.com/dontnod/nimp/pull/75/commits/a2c224ab46b507423e747b1216570867d7fd115d can be ignored for review as it's mostly extracting current logic into two classes for cleaner code.
> Symbol upload: clean + GZIP compress

- nimp/base_commands/package.py
This open the possibility to use the package_configuration in hooks.
> package: add package_configuration to env

- nimp/base_commands/package.py
Anything else leads to a certification fail.
> Package: Verify taht ps5 patch packages are set to nwonly

- nimp/command.py
... different from class name so we can duplicates generic command names across several sub commandgroups
i.e
nimp upload-pipe steam upload
nimp upload-pipe epic upload
> Commands: add possiblity to have a custom command name

- nimp/sys/logging.py
- nimp/sys/process.py
Logging: make FilteredLogging go through all app loggers
Also revert logging changes made to nimp.process.call() logging
> Logging: make FilteredLogging go through all app loggers

- nimp/symstore.py
Helper symstore msft and sony clean functions
> Builds: add helper sym clean functions

- nimp/base_commands/check.py
- setup.py
- Rewrite process listing using https://psutil.readthedocs.io/en/latest/index.html#
- Add filter check of process open file handles
- drop the unnecessary `is_unreal`
> check processes: check for process open file handles

- nimp/sys/process.py
Also allow to forward any Popen args that does not conflict with ones needed by log processing.
> process: allow to provide a callback to capture_output for custom processing
